import type { AppData, DocumentRecord, LandRecord, NotificationItem, User, AuditLog, SystemSettings } from "@/lib/types";

export const defaultUsers: User[] = [
  {
    id: "usr-1001",
    name: "Aarav Nair",
    email: "super.admin@example.com",
    role: "SUPER_ADMIN",
    department: "State IT Cell",
    isActive: true,
    permissions: [
      "MANAGE_USERS",
      "MANAGE_DEPARTMENTS",
      "VIEW_ANALYTICS",
      "VIEW_AUDIT_LOGS",
      "CONFIGURE_VALIDATION_RULES",
      "MANAGE_DOCUMENT_TYPES",
    ],
    lastLogin: "2026-09-26T08:15:00.000Z",
  },
  {
    id: "usr-1002",
    name: "Meera Patil",
    email: "government.officer@example.com",
    role: "GOVERNMENT_OFFICER",
    department: "Revenue Department",
    isActive: true,
    permissions: ["VIEW_ASSIGNED_RECORDS", "APPROVE_RECORDS", "VIEW_ANALYTICS", "GENERATE_REPORTS"],
    lastLogin: "2026-09-26T07:40:00.000Z",
  },
  {
    id: "usr-1003",
    name: "Aniket Kulkarni",
    email: "verification.officer@example.com",
    role: "VERIFICATION_OFFICER",
    department: "Land Verification Cell",
    isActive: true,
    permissions: ["REVIEW_EXTRACTIONS", "APPROVE_VERIFICATION", "FLAG_INCONSISTENCIES"],
    lastLogin: "2026-09-26T06:50:00.000Z",
  },
  {
    id: "usr-1004",
    name: "Sakshi Sharma",
    email: "data.entry@example.com",
    role: "DATA_ENTRY_OPERATOR",
    department: "District Record Desk",
    isActive: true,
    permissions: ["UPLOAD_DOCUMENTS", "ENTER_METADATA", "CORRECT_OCR", "SUBMIT_RECORDS"],
    lastLogin: "2026-09-26T05:30:00.000Z",
  },
  {
    id: "usr-1005",
    name: "Public User",
    email: "citizen@example.com",
    role: "CITIZEN",
    department: "Public Access",
    isActive: true,
    permissions: ["VIEW_PUBLIC_RECORDS", "VIEW_APPLICATION_STATUS"],
    lastLogin: "2026-09-26T04:45:00.000Z",
  },
];

const currentDate = () => new Date().toISOString();

export const defaultAuditLogs: AuditLog[] = [
  {
    id: "audit-001",
    userId: "usr-1003",
    userName: "Aniket Kulkarni",
    action: "LOGIN",
    timestamp: currentDate(),
    ipAddress: "10.0.0.4",
    device: "Chrome on Windows",
  },
  {
    id: "audit-002",
    userId: "usr-1004",
    userName: "Sakshi Sharma",
    action: "DOCUMENT_UPLOADED",
    recordId: "doc-1001",
    timestamp: currentDate(),
    ipAddress: "10.0.0.12",
    device: "Edge on Linux",
  },
];

export const defaultNotifications: NotificationItem[] = [
  {
    id: "ntf-001",
    title: "Verification required",
    message: "Property record BR-23014 has pending verification review.",
    type: "WARNING",
    read: false,
    createdAt: "2026-09-26T08:00:00.000Z",
  },
  {
    id: "ntf-002",
    title: "Document processed",
    message: "New upload from Pune district has completed OCR and extraction.",
    type: "SUCCESS",
    read: true,
    createdAt: "2026-09-25T14:00:00.000Z",
  },
  {
    id: "ntf-003",
    title: "Validation error",
    message: "Duplicate survey number flagged in record GJ-4421.",
    type: "ERROR",
    read: false,
    createdAt: "2026-09-25T16:30:00.000Z",
  },
];

export const defaultDocuments: DocumentRecord[] = [
  {
    id: "doc-1001",
    title: "7/12 Extract - Shivajinagar",
    documentType: "7/12 Extract",
    fileName: "shivajinagar-712.pdf",
    mimeType: "application/pdf",
    size: 2250000,
    uploadedBy: "usr-1004",
    uploadedAt: "2026-09-24T10:20:00.000Z",
    status: "VALIDATED",
    verificationStatus: "IN_REVIEW",
    metadata: { state: "Maharashtra", district: "Pune", taluka: "Pune City", village: "Shivajinagar" },
    rawText: "Survey Number 123/4A, Owner Rahul Sharma, Area 1450 sq. mt.",
    confidence: 0.92,
    pageCount: 2,
    recordId: "land-1001",
  },
  {
    id: "doc-1002",
    title: "Property Card - Kharadi",
    documentType: "Property Card",
    fileName: "kharadi-property-card.jpg",
    mimeType: "image/jpeg",
    size: 1800000,
    uploadedBy: "usr-1004",
    uploadedAt: "2026-09-23T09:30:00.000Z",
    status: "VERIFIED",
    verificationStatus: "VERIFIED",
    metadata: { state: "Maharashtra", district: "Pune", taluka: "Haveli", village: "Kharadi" },
    rawText: "Property registered to Ramesh Patil, survey 745/B.",
    confidence: 0.95,
    pageCount: 1,
    recordId: "land-1002",
  },
  {
    id: "doc-1003",
    title: "Sale Deed - Nashik",
    documentType: "Sale Deed",
    fileName: "nashik-sale-deed.png",
    mimeType: "image/png",
    size: 2200000,
    uploadedBy: "usr-1004",
    uploadedAt: "2026-09-20T14:10:00.000Z",
    status: "PROCESSING",
    verificationStatus: "PENDING",
    metadata: { state: "Maharashtra", district: "Nashik", taluka: "Nashik", village: "Makhmalabad" },
    rawText: "Pending OCR execution.",
    confidence: 0.62,
    pageCount: 3,
    recordId: "land-1003",
  },
];

export const defaultLandRecords: LandRecord[] = [
  {
    id: "land-1001",
    propertyId: "BR-23014",
    surveyNumber: "123/4A",
    gatNumber: "GAT-22/98",
    ownerName: "Rahul Sharma",
    coOwnerNames: ["Neha Sharma"],
    fatherName: "Rakesh Sharma",
    village: "Shivajinagar",
    taluka: "Pune City",
    district: "Pune",
    state: "Maharashtra",
    area: 1450,
    landType: "Agricultural",
    landUse: "Cultivable",
    ownershipType: "Individual",
    mutationNumber: "MUT-1402",
    documentNumber: "DOC-712-4401",
    registrationDate: "2021-06-10",
    lastUpdated: "2026-09-26T08:12:00.000Z",
    address: "Shivajinagar, Pune",
    latitude: 18.5314,
    longitude: 73.8475,
    verificationStatus: "IN_REVIEW",
    documentType: "7/12 Extract",
    extractedFields: [
      { field: "Owner Name", value: "Rahul Sharma", confidence: 0.94, source_page: 1, status: "verified" },
      { field: "Survey Number", value: "123/4A", confidence: 0.85, source_page: 1, status: "review" },
      { field: "Village", value: "Shivajinagar", confidence: 0.96, source_page: 1, status: "verified" },
      { field: "District", value: "Pune", confidence: 0.93, source_page: 1, status: "verified" },
      { field: "Area", value: "1450", confidence: 0.78, source_page: 2, status: "review" },
    ],
    validationResults: [
      {
        ruleId: "RULE-OWNER-NAME",
        field: "Owner Name",
        severity: "MEDIUM",
        description: "Potential owner name inconsistency detected by comparison with previous record.",
        expectedValue: "Rahul Sharma",
        detectedValue: "Rahil Sharma",
        status: "WARN",
      },
      {
        ruleId: "RULE-AREA-MISMATCH",
        field: "Area",
        severity: "LOW",
        description: "Area difference within tolerance band.",
        expectedValue: "1500 sq mt",
        detectedValue: "1450 sq mt",
        status: "WARN",
      },
    ],
    comments: ["Potential inconsistency detected in owner name; officer review required."],
  },
  {
    id: "land-1002",
    propertyId: "MH-PN-308",
    surveyNumber: "745/B",
    gatNumber: "GAT-12/40",
    ownerName: "Ramesh Patil",
    coOwnerNames: [],
    fatherName: "Dhondiram Patil",
    village: "Kharadi",
    taluka: "Haveli",
    district: "Pune",
    state: "Maharashtra",
    area: 2100,
    landType: "Residential",
    landUse: "Built-up",
    ownershipType: "Individual",
    mutationNumber: "MUT-1010",
    documentNumber: "DOC-PR-147",
    registrationDate: "2019-02-14",
    lastUpdated: "2026-09-25T16:00:00.000Z",
    address: "Kharadi, Pune",
    latitude: 18.5522,
    longitude: 73.9285,
    verificationStatus: "VERIFIED",
    documentType: "Property Card",
    extractedFields: [
      { field: "Owner Name", value: "Ramesh Patil", confidence: 0.97, source_page: 1, status: "verified" },
      { field: "Survey Number", value: "745/B", confidence: 0.92, source_page: 1, status: "verified" },
      { field: "District", value: "Pune", confidence: 0.98, source_page: 1, status: "verified" },
    ],
    validationResults: [],
    comments: ["No issues found after verification."],
  },
  {
    id: "land-1003",
    propertyId: "MH-NS-019",
    surveyNumber: "331/9",
    gatNumber: "GAT-44/11",
    ownerName: "Priya Joshi",
    coOwnerNames: ["Vikram Joshi"],
    fatherName: "Narayan Joshi",
    village: "Makhmalabad",
    taluka: "Nashik",
    district: "Nashik",
    state: "Maharashtra",
    area: 950,
    landType: "Agricultural",
    landUse: "Cultivable",
    ownershipType: "Joint",
    mutationNumber: "MUT-1560",
    documentNumber: "DOC-SD-9901",
    registrationDate: "2022-11-22",
    lastUpdated: "2026-09-20T11:00:00.000Z",
    address: "Makhmalabad, Nashik",
    latitude: 20.0012,
    longitude: 73.7869,
    verificationStatus: "PENDING",
    documentType: "Sale Deed",
    extractedFields: [
      { field: "Owner Name", value: "Priya Joshi", confidence: 0.88, source_page: 1, status: "review" },
      { field: "Survey Number", value: null, confidence: 0.0, source_page: 1, status: "missing" },
      { field: "Village", value: "Makhmalabad", confidence: 0.90, source_page: 1, status: "verified" },
    ],
    validationResults: [
      {
        ruleId: "RULE-MISSING-FIELD",
        field: "Survey Number",
        severity: "HIGH",
        description: "Required field missing from extraction output.",
        expectedValue: "Survey number must be present.",
        detectedValue: "null",
        status: "FAIL",
      },
    ],
    comments: ["Awaiting reprocessing of survey number field."],
  },
  {
    id: "land-1004",
    propertyId: "MH-NG-552",
    surveyNumber: "88/2C",
    gatNumber: "GAT-19/02",
    ownerName: "Sunita Deshmukh",
    coOwnerNames: ["Kishore Deshmukh"],
    fatherName: "Vasantrao Deshmukh",
    village: "Ramtek",
    taluka: "Ramtek",
    district: "Nagpur",
    state: "Maharashtra",
    area: 3400,
    landType: "Commercial",
    landUse: "Warehousing",
    ownershipType: "Joint",
    mutationNumber: "MUT-2041",
    documentNumber: "DOC-PC-8821",
    registrationDate: "2023-04-18",
    lastUpdated: "2026-09-26T09:00:00.000Z",
    address: "Ramtek Road, Nagpur",
    latitude: 21.3965,
    longitude: 79.3284,
    verificationStatus: "VERIFIED",
    documentType: "Property Card",
    extractedFields: [
      { field: "Owner Name", value: "Sunita Deshmukh", confidence: 0.98, source_page: 1, status: "verified" },
      { field: "Survey Number", value: "88/2C", confidence: 0.96, source_page: 1, status: "verified" },
      { field: "District", value: "Nagpur", confidence: 0.99, source_page: 1, status: "verified" },
      { field: "Area", value: "3400", confidence: 0.95, source_page: 1, status: "verified" },
    ],
    validationResults: [],
    comments: ["Verified and approved by Revenue Officer."],
  },
  {
    id: "land-1005",
    propertyId: "MH-TH-901",
    surveyNumber: "402/1",
    gatNumber: "GAT-08/14",
    ownerName: "Rajendra More",
    coOwnerNames: [],
    fatherName: "Baban More",
    village: "Kalyan West",
    taluka: "Kalyan",
    district: "Thane",
    state: "Maharashtra",
    area: 1820,
    landType: "Residential",
    landUse: "Housing Plot",
    ownershipType: "Individual",
    mutationNumber: "MUT-3389",
    documentNumber: "DOC-712-9012",
    registrationDate: "2024-01-12",
    lastUpdated: "2026-09-26T07:30:00.000Z",
    address: "Kalyan, Thane",
    latitude: 19.2403,
    longitude: 73.1305,
    verificationStatus: "ISSUES",
    documentType: "7/12 Extract",
    extractedFields: [
      { field: "Owner Name", value: "Rajendra More", confidence: 0.91, source_page: 1, status: "verified" },
      { field: "Survey Number", value: "402/1", confidence: 0.89, source_page: 1, status: "verified" },
      { field: "Area", value: "1820", confidence: 0.72, source_page: 2, status: "review" },
      { field: "District", value: "Thane", confidence: 0.95, source_page: 1, status: "verified" },
    ],
    validationResults: [
      {
        ruleId: "RULE-AREA-MISMATCH",
        field: "Area",
        severity: "MEDIUM",
        description: "Area recorded does not match survey map registry bounds.",
        expectedValue: "1750 sq mt",
        detectedValue: "1820 sq mt",
        status: "WARN",
      },
    ],
    comments: ["Discrepancy in recorded boundary area."],
  },
];

export const defaultSettings: SystemSettings = {
  autoOcrEnabled: true,
  strictValidation: true,
  maxAreaThreshold: 100000,
  allowedDocumentTypes: ["7/12 Extract", "Property Card", "Sale Deed", "Mutation Record", "8A Khatauni"],
  departmentName: "Revenue & Land Records Department",
  stateName: "Maharashtra",
};

export const defaultAppData: AppData = {
  users: defaultUsers,
  documents: defaultDocuments,
  landRecords: defaultLandRecords,
  notifications: defaultNotifications,
  auditLogs: defaultAuditLogs,
  settings: defaultSettings,
};
